routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PostController@welcome')->name('welcome');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/like{post_id}', 'LikeController@like')->name('like');
Route::get('/dislike{post_id}', 'DislikeController@dislike')->name('dislike');

Route::get('/my-posts', 'PostController@posts')->name('my-posts');
Route::get('/videos', 'PostController@videos')->name('videos');
Route::get('/pictures', 'PostController@images')->name('images');

Route::get('/messages', 'MessageController@index')->name('messages');
Route::post('send-message', 'MessageController@sendMessage')->name('send-message');

Route::post('add-friend{id}', 'UserController@add')->name('add-friend');
Route::post('delete-request{id}', 'UserController@deleteRequest')->name('delete-request');
Route::post('confirm', 'FriendController@confirm')->name('confirm');
Route::post('delete-friend{id}', 'FriendController@destroy')->name('delete-friend');
Route::get('search', 'FriendController@search')->name('search');

Route::resource('posts', 'PostController', ['except' => ['create', 'edit', 'show']]);
Route::resource('comments', 'CommentController', ['except' => ['create', 'edit', 'show']]);
Route::resource('users', 'UserController', ['only' => ['edit', 'update', 'destroy']]);
Route::resource('likes', 'LikeController', ['only' => ['store']]);
Route::resource('dislikes', 'DislikeController', ['only' => ['store']]);

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }

    public function image()
    {
        return $this->morphOne('App\Image', 'imageable');
    }

    public function likes()
    {
        return $this->hasMany('App\Like');
    }

    public function dislikes()
    {
        return $this->hasMany('App\Dislike');
    }

    public function messages()
    {
        return $this->hasMany(Message::class);
    }

    public function hasLikedPost(Post $post)
    {
        return $post->likes()
            ->where('likeable_id', $post->id)
            ->where('likeable_type', get_class($post))
            ->where('user_id', $this->id)
            ->count();
    }

    public function hasDislikedPost(Post $post)
    {
        return $post->dislikes()
            ->where('dislikeable_id', $post->id)
            ->where('dislikeable_type', get_class($post))
            ->where('user_id', $this->id)
            ->count();
    }

    public function friendsOfMine()
    {
        return $this->belongsToMany('App\User', 'friends', 'user_id', 'friend_id');
    }

    public function friendOf()
    {
        return $this->belongsToMany('App\User', 'friends','friend_id', 'user_id');
    }

    public function friends()
    {
        return $this->friendsOfMine()->wherePivot('confirm', 1)->get()->merge($this->friendOf()->wherePivot('confirm', 1)->get());
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Events\SendRequestForFriendEvent;
use App\Events\UpdateUserEvent;
use App\Http\Requests\UpdateUserRequest;
use App\RequestForFriend;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    public function edit(User $user)
    {
        return view('users.profile', ['user' => $user]);
    }

    public function update(UpdateUserRequest $request, User $user)
    {
        $userUpdateEvent = new UpdateUserEvent();
        $userUpdateEvent->setRequest($request);
        $userUpdateEvent->setUser($user);
        event($userUpdateEvent);

        return redirect()->route('home');
    }

    public function add($id)
    {
        $sendRequestForFriend = new SendRequestForFriendEvent();
        $sendRequestForFriend->setId($id);
        event($sendRequestForFriend);
        return redirect()->back();
    }

    public function deleteRequest($id)
    {
        $request = RequestForFriend::find($id);
        $request->delete();
        return redirect()->back();
    }
}

resources/views/users/messages.blade.php
@extends('layouts.main')

@section('content')
    <div class="theme-layout">
        <section>
            <div class="gap gray-bg">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row" id="page-contents">
                                @include('includes.sidebar')
                                <div class="col-lg-6">
                                    <div class="widget friend-list stick-widget">
                                        <h4 class="widget-title">Messages</h4>
                                        <ul id="people-list" class="friendz-list">
                                            @foreach($users as $user)
                                                <li class="mt-5">
                                                    <div class="col-lg-6">
                                                        <aside class="sidebar static">
                                                            <div class="widget">
                                                            @foreach($user->messages as $message)
                                                                    <p class="m-2">{{ $message->message }}</p>
                                                            @endforeach
                                                            </div>
                                                        </aside>
                                                    </div>
                                                    @if($user->image)
                                                        <figure>
                                                            <a href="#" title=""><img src="storage/{{ $user->image->image }}" alt="" width="48px;"></a>
                                                            <p style="display: contents">{{ $user->name }}</p>
                                                        </figure>
                                                    @else
                                                        <figure>
                                                            <a href="#" title=""><img src="images/resources/friend-avatar6.jpg" alt=""></a>
                                                            <p style="display: contents">{{ $user->name }}</p>
                                                        </figure>
                                                    @endif
                                                </li>
                                                <div class="friendz-meta mt-2 float-right">
                                                    <div class="newpst-input">
                                                        <div class="col-lg-6">
                                                            <aside class="sidebar static">
                                                                <div class="widget">
                                                                    @foreach(auth()->user()->messages as $message)
                                                                        <p class="m-2">{{ $message->message }}</p>
                                                                    @endforeach
                                                                </div>
                                                            </aside>
                                                        </div>
                                                        @if(auth()->user()->image)
                                                            <figure class="float-right">
                                                                <a href="#" title=""><img src="storage/{{ auth()->user()->image->image }}" alt=""></a>
                                                                <p style="display: contents">{{ auth()->user()->name }}</p>
                                                            </figure>
                                                        @else
                                                                <figure class="float-right">
                                                                    <a href="#" title=""><img src="images/resources/friend-avatar5.jpg" alt=""></a>
                                                                    <p style="display: contents">{{ auth()->user()->name }}</p>
                                                                </figure>
                                                        @endif
                                                        <form method="POST" action="{{ route('send-message') }}" enctype="multipart/form-data">
                                                            @csrf
                                                            @method('POST')
                                                            <input type="hidden" name="data[{{ $loop->index }}][friend_id]" value="{{ $user->id }}">
                                                            <input type="hidden" name="data[{{ $loop->index }}][user_id]" value="{{ auth()->user()->id }}">
                                                            <textarea rows="2" placeholder="write something" name="data[{{ $loop->index }}][message]"></textarea>
                                                            <button type="submit" class="btn-sm mt-2 float-right">Send Message</button>
                                                        </form>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </ul>
                                    </div><!-- friends list sidebar -->
                                </div><!-- centerl meta -->
                                @include('includes.mypage')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/users/profile.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Profile') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('users.update', $user->id) }}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="form-group row">
                                <label class="col-md-4 col-form-label text-md-right">Profile Picture</label>
                                <div class="col-md-6">
                                <input name="image" type="file">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>
                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" autocomplete="name" autofocus>
                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" autocomplete="email">

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" autocomplete="new-password">

                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" autocomplete="new-password">
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Update') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection