routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PostController@welcome')->name('welcome');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/like{post_id}', 'LikeController@like')->name('like');
Route::get('/dislike{post_id}', 'DislikeController@dislike')->name('dislike');

Route::get('/my-posts', 'PostController@posts')->name('my-posts');
Route::get('/videos', 'PostController@videos')->name('videos');
Route::get('/pictures', 'PostController@images')->name('images');

Route::get('/messages', 'MessageController@index')->name('messages');
Route::post('send-message', 'MessageController@sendMessage')->name('send-message');

Route::post('add-friend{id}', 'UserController@add')->name('add-friend');
Route::post('delete-request{id}', 'UserController@deleteRequest')->name('delete-request');
Route::post('confirm', 'FriendController@confirm')->name('confirm');
Route::post('delete-friend{id}', 'FriendController@destroy')->name('delete-friend');
Route::get('search', 'FriendController@search')->name('search');

Route::resource('posts', 'PostController', ['except' => ['create', 'edit', 'show']]);
Route::resource('comments', 'CommentController', ['except' => ['create', 'edit', 'show']]);
Route::resource('users', 'UserController', ['only' => ['edit', 'update', 'destroy']]);
Route::resource('likes', 'LikeController', ['only' => ['store']]);
Route::resource('dislikes', 'DislikeController', ['only' => ['store']]);

resources/views/includes/content.blade.php
<div class="col-lg-6">
    @include('includes.post')
    @foreach($posts as $post)
        <div class="central-meta item">
            <div class="user-post">
                <div class="friend-info">
                    @if(isset($post->user->image))
                        <figure>
                            <img src="storage/{{ $post->user->image->image }}" alt="">
                        </figure>
                    @else
                        <figure>
                            <img src="{{ asset('images/resources/friend-avatar5.jpg') }}" alt="">
                        </figure>
                    @endif
                    <div class="friend-name">
                        <p>{{ $post->user->name }}</p>
                        <span>{{ $post->user->created_at }}</span>
                    </div>
                    <div class="post-meta">
                        @if(isset($post->image))
                            <img src="storage/{{ $post->image->image }}" alt="">
                        @elseif (isset($post->video))
                            <video width="875" height="500" controls>
                                <source src="storage/{{ $post->video }}">
                            </video>
                        @endif
                        <div class="we-video-info">
                            <ul>
                                <li>
                                    <span class="comment" data-toggle="tooltip" title="Comments">
                                        <i class="fa fa-comments-o"></i>
                                        <ins>{{ count($post->comments) }}</ins>
                                    </span>
                                </li>
                                <li>
                                    <span class="like" data-toggle="tooltip" title="like">
                                        <a href="{{ route('like', $post->id) }}">
                                            <i  class="ti-heart"></i>
                                            <ins>{{ count($post->likes) }}</ins>
                                        </a>
                                    </span>

                                </li>
                                <li>
                                    <span class="dislike" data-toggle="tooltip" title="dislike">
                                        <a href="{{ route('dislike', $post->id) }}">
                                            <i  class="ti-heart-broken"></i>
                                            <ins>{{ count($post->dislikes) }}</ins>
                                        </a>
                                    </span>

                                </li>
{{--                                <li>--}}
{{--                                    <span class="dislike" data-toggle="tooltip" title="dislike">--}}
{{--                                        <button onclick="dislikeCounter()" class="ti-heart-broken"></button>--}}
{{--                                    </span>--}}
{{--                                    <ins id="dislike" class="mb-2"></ins>--}}
{{--                                </li>--}}
                            </ul>
                        </div>
                        <div class="description">
                            <p>
                                {{ $post->content }}
                            </p>
                        </div>
                        <form action="{{ route('comments.store') }}" method="POST">
                            @csrf
                            @method('POST')
                            <div class="mb-3">
                                <input type="hidden" name="postId" id="postId" value="{{ $post->id }}">
                                <label for="body">Comments</label> {{ count($post->comments) }}
                                @foreach($post->comments as $comment)
                                    <p>&nbsp;
                                        <span class="font-weight-bold">{{ $comment->user->name }}</span>: {{ $comment->comment }}
                                    </p>
                                @endforeach
                                <textarea class="form-control" name="body" id="body"
                                          style=" min-width: 500px;"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Comment</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
</div><!-- centerl meta -->

resources/views/includes/mypage.blade.php
<div class="col-lg-3">
    <aside class="sidebar static">
        <div class="widget">
            <h4 class="widget-title">New Users</h4>
            <ul id="people-list" class="friendz-list">
                @foreach($users as $user)
                <li>
                    <a class="dropdown-item" href="{{ route('add-friend', $user->id) }}"
                       onclick="event.preventDefault();
                                                 document.getElementById('form').submit();">
                    </a>
                </li>
                    @if($user->image)
                        <figure>
                            <a href="#" title=""><img src="storage/{{ $user->image->image }}" alt=""></a>
                        </figure>
                    @else
                        <figure>
                            <a href="#" title=""><img src="{{ asset('images/resources/friend-avatar6.jpg') }}" alt=""></a>
                        </figure>
                    @endif
                    <div class="friendz-meta">
                        <p style="display: contents">{{ $user->name }}</p>
                        <div style="float: right">
                            <form action="{{ route('add-friend', $user->id) }}" style="display: contents" method="POST" enctype="multipart/form-data" id="form">
                                @csrf
                                @method('POST')
                                <button type="submit" class="btn-sm btn-primary">Add</button>
                            </form>
                            <form style="display: contents">
                                <button type="submit" class="btn-sm btn-primary">Delete</button>
                            </form>
                        </div>
                    </div>
                @endforeach
            </ul>
        </div><!-- all users sidebar -->
        <div class="widget friend-list stick-widget">
                <h4 class="widget-title">Friend Requests</h4>
                <div class="tab-pane" id="frends-req">
                <ul class="nearby-contct">
                    @foreach($requests as $request)
                        <div class="nearly-pepls ml-4">
                            @if(!$request->user->image)
                                <figure>
                                    <a href="#" title=""><img src="{{ asset('images/resources/friend-avatar6.jpg') }}" alt=""></a>
                                    <a href="#" title="" style="display: contents">{{ $request->user->name }}</a>
                                </figure>
                            @else
                                <figure>
                                    <a href="#" title=""><img src="storage/{{ $request->user->image->image }}" alt=""></a>
                                    <a href="#" title="" style="display: contents">{{ $request->user->name }}</a>
                                </figure>
                            @endif
                            <div class="friendz-meta" style="display: contents">
                                <form method="POST" style="display: contents;" action="{{ route('confirm') }}" id="form-confirm">
                                    @csrf
                                    <input type="hidden" name="request_id" value="{{ $request->id }}">
                                    <button type="submit" class="btn-sm btn-success" data-ripple="">Accept</button>
                                </form>
                                <form style="display: contents;" action="{{ route('delete-request', $request->id) }}" method="POST">
                                    @csrf
                                    <button class="btn-sm btn-danger" data-ripple="">Cancel</button>
                                </form>
                            </div>
                            <li>
                                <a class="dropdown-item" href="{{ route('confirm')}}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('form-confirm').submit();">
                                </a>
                            </li>
                        </div>
                    @endforeach
                </ul>
            </div>
        </div><!-- friends requests sidebar -->

    </aside>
</div><!-- sidebar -->

resources/views/includes/post.blade.php
<div class="central-meta">
    <div class="new-postbox">
        @if(auth()->user()->image)
            <figure class="float-left">
                <a href="#" title=""><img src="storage/{{ auth()->user()->image->image }}" alt=""></a>
                <p style="display: contents">{{ auth()->user()->name  }}</p>
            </figure>
        @else
            <figure class="float-right">
                <a href="#" title=""><img src="images/resources/friend-avatar5.jpg" alt=""></a>
                <p style="display: contents">{{ auth()->user()->name }}</p>
            </figure>
        @endif
        <div class="newpst-input">
            <form method="POST" action="{{ route('posts.store') }}" enctype="multipart/form-data">
                @csrf
                @method('POST')
                <textarea rows="2" placeholder="write something" name="content"></textarea>
                <div class="attachments">
                    <ul>
                        <li>
                            <i class="fa fa-image"></i>
                            <label class="fileContainer" for="image">
                                <input type="file" name="image" id="image">
                            </label>
                        </li>
                    </ul>
                </div>
                <button type="submit" class="btn-sm mt-1">Post</button>
            </form>
        </div>
    </div>
</div><!-- add post new box -->

resources/views/includes/sidebar.blade.php
<div class="col-lg-3">
    <aside class="sidebar static">
        <div class="widget">
            <h4 class="widget-title">Profile</h4>
            <div class="your-page">
                @if(auth()->user()->image)
                    <figure>
                        <a href="#" title=""><img src="storage/{{ auth()->user()->image->image }}" alt=""></a>
                    </figure>
                @else
                    <figure>
                        <a href="#" title=""><img src="images/resources/friend-avatar5.jpg" alt=""></a>
                    </figure>
                @endif
                <div class="page-meta">
                    <a href="#" class="underline">{{ auth()->user()->name }}</a>
                </div>
            </div>
            <ul class="naves mt-3">
                <li>
                    <i class="ti-clipboard"></i>
                    <a href="{{ route('home') }}" title="">Home</a>
                </li>
                <li>
                    <i class="ti-files"></i>
                    <a href="{{ route('my-posts') }}" title="">My posts</a>
                <li>
                    <i class="ti-image"></i>
                    <a href="{{ route('images') }}" title="">images</a>
                </li>
                <li>
                    <i class="ti-comments-smiley"></i>
                    <a href="{{ route('messages') }}" title="">Messages</a>
                </li>
            </ul>
        </div><!-- Shortcuts -->
        <div class="widget friend-list stick-widget">
            <h4 class="widget-title">Friends</h4>
            <ul id="people-list" class="friendz-list">
                @if(!count($friends))
                    <p>You have no friends</p>
                @else
                    @foreach($friends as $friend)
                        <li>
                            <a class="dropdown-item" href="{{ route('delete-friend', $friend->id) }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('cancel').submit();">
                            </a>
                        </li>
                        @if($friend->image)
                            <figure>
                                <a href="#" title=""><img src="storage/{{ $friend->image->image}}" alt=""></a>
                            </figure>
                        @else
                            <figure>
                                <a href="#" title=""><img src="{{ asset('images/resources/friend-avatar6.jpg') }}" alt=""></a>
                            </figure>
                        @endif
                        <div class="friendz-meta">
                            <p style="display: contents">{{ $friend->name}}</p>
                            <div style="float: right">
                                <form action="{{ route('delete-friend', $friend->id) }}" style="display: contents" method="POST" enctype="multipart/form-data" id="cancel">
                                    @csrf
                                    @method('POST')
                                    <button type="submit" class="btn-sm btn-primary">Delete</button>
                                </form>
                            </div>
                        </div>
                    @endforeach
                @endif
            </ul>
        </div><!-- friends list sidebar -->
    </aside>
</div><!-- sidebar -->